name: Build and run Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-nginx-app .

      - name: Run Docker container
        run: docker run -d --name my-nginx-app my-nginx-app
